Create Automatic Differentiation
gnu-octave/packages pull request #138
Opened 2022-07-15 06:22 UTC by StevenWaldrip

See https://octave.discourse.group/t/automatic-differentiation/2078
First time trying to add a package so don't know what I'm doing.

2022-07-15 13:49 UTC, mmuetzel requested changes
Not a complete review. Just some remarks.

2022-07-15 13:49 UTC, mmuetzel commented on packages/Automatic Differentiation
> +icon: "https://raw.githubusercontent.com/gnu-octave/pkg-example/main/doc/icon.png"
If you have an icon that could represent your package, you could point to it here.
This is the icon that is shown for the package in the index.
Currently, that is this icon:
https://raw.githubusercontent.com/gnu-octave/pkg-example/main/doc/icon.png

2022-07-15 13:49 UTC, mmuetzel commented on packages/Automatic Differentiation
> +  url: "https://github.com/StevenWaldrip/Automatic-Differentiation/blob/main/LICENSE"
Afaict, the file has been renamed to `COPYING`.

2022-07-15 13:49 UTC, mmuetzel commented on packages/Automatic Differentiation
> +  - "pkg"
Remove this block. This is just the example from the template.
IIUC, the top element in the `versions` section of this file is the one that will be displayed as the main one in the package index.

2022-07-15 13:49 UTC, mmuetzel commented on packages/Automatic Differentiation
> +  url: "https://github.com/StevenWaldrip/Automatic-Differentiation"
This should probably be https://github.com/StevenWaldrip/Automatic-Differentiation/archive/refs/heads/main.zip

2022-07-15 13:49 UTC, mmuetzel commented on packages/Automatic Differentiation
> +  url: "https://github.com/StevenWaldrip/Automatic-Differentiation"
Once you have added a tag for your first version, add the link to its source tarball here.

2022-07-15 13:49 UTC, mmuetzel commented on packages/Automatic Differentiation
> +  date: "2020-09-02"
Adjust the date for the first release.

2022-07-17 08:39 UTC, mmuetzel approved these changes

2022-07-17 08:42 UTC, mmuetzel commented
Looks good to me.

@siko1056: It looks like the CI was skipped. Do you know why?

2022-07-17 09:20 UTC, siko1056 commented
@mmuetzel The reason was that the package file was not matching the guidelines

```
packages/Automatic-Differentiation
packages/automatic-differentiation.yaml
```

Thus the CI pipeline ignored that change (for example changes I do on the website itself are also ignored).

2022-07-17 09:22 UTC, merged

2022-07-17 09:23 UTC, siko1056 commented
@StevenWaldrip congratulations for your package publication :tada: and @mmuetzel thank you for all you on-boarding guidance :slightly_smiling_face: :+1: